insert into user
values (101, 'Tom');
insert into user
values (102, 'Andrew');
insert into user
values (103, 'Tony');
insert into user
values (104, 'Bob');
insert into user
values (105, 'Sam');